# Generated by Django 5.0.3 on 2024-03-09 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDF_Details',
            new_name='File_Details',
        ),
    ]
