# Generated by Django 5.0.3 on 2024-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfchat', '0002_rename_pdf_details_file_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
