# Generated by Django 5.0.3 on 2024-03-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfchat', '0004_alter_file_details__id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Details',
            fields=[
                ('_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files/')),
                ('thread_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='File_Details',
        ),
    ]
